CXX = g++
CXXFLAGS = -std=c++17 -Wall -g

SRC = /src/main.cpp /src/Partition/Partition.cpp

OBJ = $(SRC:.cpp=.o)

EXEC = bootable_usb_program

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CXX) $(OBJ) -o $(EXEC)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)
